name: My Jobs
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: [self-hosted]
    env:
      CONTAINER_NAME: myappCommandContainer
    steps:
      # Check out the code from the repository
      - uses: actions/checkout@v3
      
      # Build Docker image
      - name: Build Docker Image
        run: |
          echo ":: Building Docker image..."
          docker build -t myapp:latest -f ./Dockerfile .
      
      # List Docker images
      - name: List Docker Images
        run: |
          echo ":: Listing Docker images..."
          docker images

      # Manage Docker container and build
      - name: Manage Docker Container
        run: |
          CNAME=${{ env.CONTAINER_NAME }}
          
          # Check if the container exists
          if [ "$(docker ps -aq -f name=$CNAME)" ]; then
              if [ "$(docker ps -aq -f status=exited -f name=$CNAME)" ]; then
                  echo ":: Container $CNAME exists and is exited"
                  echo ":: Removing exited container - $CNAME"
                  docker rm $CNAME
              else
                  echo ":: Container $CNAME exists and is running"
                  echo ":: Stopping running container - $CNAME"
                  docker stop $CNAME
                  echo ":: Removing stopped container - $CNAME"
                  docker rm $CNAME
              fi
          else
              echo ":: No existing container named $CNAME"
          fi

          # Run new container
          echo ":: Running new container - $CNAME"
          docker run -d -p 8080:8080 --name $CNAME myapp:latest

      # Optionally, you can add a step to verify if the container is running
      - name: Verify Container Status
        run: |
          CNAME=${{ env.CONTAINER_NAME }}
          echo ":: Checking the status of the container - $CNAME"
          if [ "$(docker ps -q -f name=$CNAME)" ]; then
              echo ":: Container $CNAME is running."
          else
              echo ":: Container $CNAME is not running."
              exit 1 # Fail the job if the container is not running
          fi
